### ISSUE TITLE
Question about memory consumption of add_scalars

### ISSUE THREAD

**Issue by themightyoarfish** [lanpa/tensorboardX#204]
The doc says 
> Note that this function also keeps logged scalars in memory. In extreme case it explodes your RAM.

But why is this so? The code seems to log everything to `self.scalar_dict` but it doesn't seem to be used in the `SummaryWriter` class, except for manual json export. Would it be reasonable to add an option to simply prevent keeping the scalars in memory?

**Comment by lanpa** [comment]
That means the code has to dump the scalars to the disk periodically. So the user needs to specify how many time/steps should the code save the data. And the `add_scalars` function needs to check for them whenever it is been called. As always, PRs are welcome!

**Comment by HamsterHuey** [comment]
@lanpa - I wanted to revisit this issue (and would be happy to submit a PR). I looked at the code in `writer.py` and here is my understanding at the moment:

1. The reason RAM usage can blow up with `add_scalars()` method is because of the invocation of `__append_to_scalar_dict()`  after logging the scalars (See line here: https://github.com/lanpa/tensorboardX/blob/master/tensorboardX/writer.py#L461)
2. `self.__append_to_scalar_dict()` method in `SummaryWriter` keeps growing the `self.scalar_dict` with every call to `add_params()`
3. `self.scalar_dict` is only ever reset when the `export_scalars_to_json()` instance method is manually invoked by the user. In normal usage, this never occurs, so RAM usage continues to grow indefinitely 
4. `add_param()` also used to have this issue as highlighted by #116 but was addressed by you with this fix: https://github.com/lanpa/tensorboardX/commit/c9a84bc32e2ca17d7bd2446736088a6181ecf5b6 that simply removed the line that resulted in the scalar being appended to `self.scalar_dict`

If my understanding of all of the above is correct, I am a bit confused about the following:

I don't quite understand the point of storing only a subset of scalars that were added via the `add_params()` method but not the `add_param()` method in memory in `self.scalar_dict`. As far as I can tell, the `export_scalars_to_json()` method is only invoked in a couple of testing scripts in this repo, and even in those, I don't see how it is doing the "right" thing if the scalars added via `add_param` are not being added to `self.scalar_dict`?

I'd be happy to submit a PR to address this if you would be interested, but I'm afraid I don't currently understand some of the factors that underly how things are structured at the moment so I'd appreciate any inputs on your end regarding the above. Thanks!

**Comment by lanpa** [comment]
@HamsterHuey , you traced the code correctly. But `add_scalar` is used to reflect `tf.summary.scalar` in the official TensorBoard, which doesn't keep the data in memory, so there is nothing added to self.scalar_dict and therefore guaranteed that memory usage will not go up after a long training. On the contrary, `add_scalars()` and `export_scalars_to_json()` are just auxiliary functions that are suitable for small experiments, hence the different code logic.

**Comment by HamsterHuey** [comment]
Thanks for the reply @lanpa , that makes sense.

**Comment by lanpa** [comment]
If you have any experimental features want to implement, welcome to contribute here, I am happy to review!
