### ISSUE TITLE
error: [Errno 13] Permission denied: './compile.sh'

### ISSUE THREAD

**Issue by InstantWindy** [lanpa/tensorboardX#298]
Hi! When I install tensorboardX under Linux, it appears “error: [Errno 13] Permission denied: './compile.sh'”,Thank you!

**Comment by lanpa** [comment]
Hi, would you share the whole console output, including the command you used? Thanks.

**Comment by InstantWindy** [comment]
![image](https://user-images.githubusercontent.com/23608180/49696018-83f54180-fbde-11e8-9a64-39c66ae156d1.png)

**Comment by lanpa** [comment]
maybe the execution bit is not set. Would you try `chmod +x compile.sh` first?

**Comment by mdraw** [comment]
I've encountered a similar issue: When trying to install tensorboardX via the .tar.gz from PyPI (https://pypi.org/project/tensorboardX/#files), it fails with

> error: [Errno 2] No such file or directory: './compile.sh': './compile.sh'

The reason for this is that it's not compile.sh is not included in the .tar.gz. I guess adding
`include compile.sh`
to https://github.com/lanpa/tensorboardX/blob/master/MANIFEST.in would fix that.

@InstantWindy's issue can probably be fixed by just replacing
https://github.com/lanpa/tensorboardX/blob/27f8e6b5e409e02bce5ded8a12adb898916ae169/setup.py#L12
with `subprocess.call(['bash', 'compile.sh'])`. This would circumvent any permission issues.
I'll test everything and send a PR if it works.

**Comment by lanpa** [comment]
`Permission denied` is different than file not found. Reopening this.

**Comment by mdraw** [comment]
I've fixed the permission issue in the other commit in my PR that you just merged, see https://github.com/lanpa/tensorboardX/commit/52ed503be6c3937e14de8356b650463ebc856c0a.

**Comment by mdraw** [comment]
I should have explained better that the two commits fix two separate issues (this one as well as the one that I reported here).

**Comment by lanpa** [comment]
Thanks, @mdraw . @InstantWindy would you try the fix? Please close the issue if it solves your problem.
