### ISSUE TITLE
hyper parameters

### ISSUE THREAD

**Issue by YoelShoshan** [lanpa/tensorboardX#381]
If it's possible, supporting the newly added hyper params feature would be amazing :)

https://www.tensorflow.org/tensorboard/r2/hyperparameter_tuning_with_hparams

**Comment by thomwolf** [comment]
👍 That would be amazing!

**Comment by diogoseca** [comment]
I'd wait for a more stabler release before attempt to add support for it. The TF API is currently changing, and is a pain in the ass to get the hparams feature to work by itself. I'm not even to replicate the same results in that article, or any other tutorial about tensorboard's hparams.

Tl;dr: I'd wait for a tf2.0 official release before adding support for it.

**Comment by eisenjulian** [comment]
Hello @diogoseca , that totally makes sense. However, I currently need this feature for a downstream application on TensorboardX that I am working on, so I went ahead and worked on it on [my fork](https://github.com/lanpa/tensorboardX/compare/master...eisenjulian:add-hparam-support?expand=1). If you find it useful I can submit a PR.

**Comment by MasanoriYamada** [comment]
@eisenjulian 
Thank you. I tried it and it was very useful.

```
pipenv install -e git+https://github.com/eisenjulian/tensorboardX.git@add-hparam-support#egg=tensorboardX
pipenv install tf-nightly-2.0-preview
```

**Comment by Neabfi** [comment]
A PR would be very useful.

**Comment by eisenjulian** [comment]
I'm happy to make the commit into a PR but would like a blessing from maintainers first.

**Comment by yorard123** [comment]
I am also interested in hparams. Is there any advance on it?

**Comment by heartcored98** [comment]
> I'm happy to make the commit into a PR but would like a blessing from maintainers first.

@eisenjulian You're the best. It's awesome. Working smoothly (in case of multi-user scnario, one might have to give chmod 777 permision to /tmp/.tensorboard-info).

You saved my ass.

**Comment by lanpa** [comment]
@eisenjulian Oh, you should open a PR directly so that I don't rebuild the wheel! I just merged my implementation. Thanks anyway!

**Comment by eisenjulian** [comment]
Hi @lanpa, sorry for the misunderstanding. I just thought if no-one replied here, nobody would reply on the PR either. Some open-source projects advise getting pre-approval from maintainers instead of directly sending the code. I'll take it into account for the next time. And I am glad that you added the feature, thanks!

**Comment by lanpa** [comment]
@eisenjulian I looked at your code (demo_hparam.py). Did you missed `add_hparam_expertiment()`?

**Comment by eisenjulian** [comment]
You're correct, I think at that point I came up with a minimal working example, and it turns out that you don't need to call `add_hparam_expertiment()` for TensorBoard to pick-up each of the different trials, but you don't get to customize the way in which each one is displayed on the left-hand side panel.
