### ISSUE TITLE
How to make graph show layer's parameters(kernel size, padding, ...) and feature map size？

### ISSUE THREAD

**Issue by haochange** [lanpa/tensorboardX#531]

**Comment by lanpa** [comment]
Hi, since the network graph interpretation is highly correlated with the PyTorch JIT (and it changes fast), the graph visualization has been delegated to the core PyTorch team. https://github.com/lanpa/tensorboardX/commit/d7238f5b1a3073a621ddf347ee1f865531d47e6c Please make this request at the PyTorch repository.
