### ISSUE TITLE
Is there an efficient way to log line plots?

### ISSUE THREAD

**Issue by pfeatherstone** [lanpa/tensorboardX#718]
Currently I'm plotting line curves using Matplotlib then using `add_figure()`. Matplotlib is super slow to render.
Is there a better way?
Just to be clear, at every time step/iteration, i want to plot a new line (not scalar)

**Comment by lanpa** [comment]
Hi, what is your average time needed for each iteration? if there are too many images logged, I am afraid that tensorboard will be very, very slow.

**Comment by pfeatherstone** [comment]
Yeah, I'm logging a lot of stuff. I was wondering if rendering my plots to image-like numpy arrays directly then using `add_image()` would be faster but haven't found a good library to do that yet

**Comment by pfeatherstone** [comment]
pyqtgraph is orders of magnitude faster than matplotlib, but again, can't find a way to log a pyqtgraph to tensoboard in some way. In theory, I could strip all the code in pyqtgraph which renders to a numpy array (before plotting using QT), then log that to tensorboard. But that seems like effort.

**Comment by lanpa** [comment]
Sorry that I didn't explain my idea clearly.
My point is that no matter how fast the "write image" functions are, as long as there are many images in the tensorboard log_dir, the loading speed will be slow, and it will be uneasy for you to see all the images you saved because of the slider tick. Since you mentioned that you want to log at every step/iteration, I guess that you are going to log maybe 10k plots in total, and most of the logged plots will not be shown on the tensorboard. If the above guess is correct, I will suggest you just pickle the raw data after each iteration and plot them as png using another matplotlib process. Once you have saved the raw data with different filename: `iter_00001_raw.pickle`, you can easily plot them in parallel.

**Comment by pfeatherstone** [comment]
At this point it's better me building my own dashboard with QT. PyQTgraph can easily plot all of this in real time. I'll close the issue. But thank you very much for your input.
